steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '.']
  secretEnv: [
    'WALLET_ADDRESS',
    'WALLET_PRIVATE_KEY',
    'API_TOKEN',
    'ALCHEMY_API_KEY',
    'SLACK_WEBHOOK0',
    'SLACK_WEBHOOK1',
    'SLACK_WEBHOOK2',
    'SENTRY_DSN0',
    'SENTRY_DSN1',
    'SENTRY_DSN2'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instance-templates', 'create-with-container', 'liquidator-template-$COMMIT_SHA', '--container-image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instance-groups', 'managed', 'rolling-action', 'start-update', 'liquidator-instance-group-3', '--version=liquidator-template-$COMMIT_SHA', '--zone=us-central1-a']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WALLET_ADDRESS/versions/latest
    env: 'WALLET_ADDRESS'
  - versionName: projects/$PROJECT_ID/secrets/WALLET_PRIVATE_KEY/versions/latest
    env: 'WALLET_PRIVATE_KEY'
  - versionName: projects/$PROJECT_ID/secrets/API_TOKEN/versions/latest
    env: 'API_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/ALCHEMY_API_KEY/versions/latest
    env: 'ALCHEMY_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/SLACK_WEBHOOK0/versions/latest
    env: 'SLACK_WEBHOOK0'
  - versionName: projects/$PROJECT_ID/secrets/SLACK_WEBHOOK1/versions/latest
    env: 'SLACK_WEBHOOK1'
  - versionName: projects/$PROJECT_ID/secrets/SLACK_WEBHOOK2/versions/latest
    env: 'SLACK_WEBHOOK2'
  - versionName: projects/$PROJECT_ID/secrets/SENTRY_DSN0/versions/latest
    env: 'SENTRY_DSN0'
  - versionName: projects/$PROJECT_ID/secrets/SENTRY_DSN1/versions/latest
    env: 'SENTRY_DSN1'
  - versionName: projects/$PROJECT_ID/secrets/SENTRY_DSN2/versions/latest
    env: 'SENTRY_DSN2'
