steps:
- name: 'ubuntu'
  dir: 'app'
  args: ['bash', './env_script.sh']
  env:
    - 'WALLET_ADDRESS=${_WALLET_ADDRESS}'
    - 'WALLET_PRIVATE_KEY=${_WALLET_PRIVATE_KEY}'
    - 'API_TOKEN=${_API_TOKEN}'
    - 'ALCHEMY_API_KEY=${_ALCHEMY_API_KEY}'
    - 'FACTORY_ADDRESS=${_FACTORY_ADDRESS}'
    - 'CREATE_ACCOUNT_TOPIC_ID=${_CREATE_ACCOUNT_TOPIC_ID}'
    - 'LIQUIDATOR_ADDRESS=${_LIQUIDATOR_ADDRESS}'
    - 'SLACK_WEBHOOK0=${_SLACK_WEBHOOK0}'
    - 'SLACK_WEBHOOK1=${_SLACK_WEBHOOK1}'
    - 'SLACK_WEBHOOK2=${_SLACK_WEBHOOK2}'
    - 'SENTRY_DSN0=${_SENTRY_DSN0}'
    - 'SENTRY_DSN1=${_SENTRY_DSN1}'
    - 'SENTRY_DSN2=${_SENTRY_DSN2}'
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'app'
  args: ['app', 'deploy', '.']
timeout: '1600s'