[profile.default]

src = 'contracts/src'
test = 'contracts/test'
libs = ['contracts/lib']

out = 'contracts/build'
cache_path = 'contracts/cache'

optimizer = true
optimizer_runs = 1000000
gas_reports = []

auto_detect_remappings = true

[fuzz]
runs = 2048
