[profile.default]

src = 'contracts/src'
test = 'contracts/test'
libs = ['contracts/lib']

out = 'contracts/build'
cache_path = 'contracts/cache'

optimizer = true
optimizer_runs = 1000000
gas_reports = []

auto_detect_remappings = true

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"
optimism = "${RPC_URL_OPTIMISM}"

[fuzz]
runs = 2048
