runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
env_variables:
  WALLET_ADDRESS: "%WALLET_ADDRESS%"
  WALLET_PRIVATE_KEY: "%WALLET_PRIVATE_KEY%"
  API_TOKEN: "%API_TOKEN%"
  ALCHEMY_API_KEY: "%ALCHEMY_API_KEY%"
  FACTORY_ADDRESS: "%FACTORY_ADDRESS%"
  CREATE_ACCOUNT_TOPIC_ID: "%CREATE_ACCOUNT_TOPIC_ID%"
  LIQUIDATOR_ADDRESS: "%LIQUIDATOR_ADDRESS%"
  SLACK_WEBHOOK0: "%SLACK_WEBHOOK0%"
  SLACK_WEBHOOK1: "%SLACK_WEBHOOK1%"
  SLACK_WEBHOOK2: "%SLACK_WEBHOOK2%"