[profile.default]

src = 'src'
test = 'test'
libs = ['lib']

out = 'build'
cache_path = 'cache'

optimizer = true
optimizer_runs = 1000000
gas_reports = []

auto_detect_remappings = true
remappings = [
    'openzeppelin-contracts/=lib/aloe-ii/core/lib/openzeppelin-contracts/contracts/',
]

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"
optimism = "${RPC_URL_OPTIMISM}"
arbitrum = "${RPC_URL_ARBITRUM}"

[fuzz]
runs = 2048
